"""Freeze gate: does requesting logprobs change the generated bytes?

The registered first-divergence / logprob-margin endpoints want logprob
capture inside the frozen greedy request bodies. That is only legal if the
`logprobs` request fields are generation-neutral: same model, same options,
same seed must yield byte-identical text with and without them. This probe
answers that empirically on the pinned engine by comparing live calls
(with logprobs fields) against the byte-identical-body pilot cells already
committed in a study3 report.

Usage:
  python3 -m harness.probe_logprobs_bytes \
      --base-url http://127.0.0.1:11435 --label cuda-4090 \
      --report reports/study3-report-20260730T004533Z.json \
      --box cuda --repeats 3

Writes evidence/logprobs-bytes-probe-<label>.json; exit 0 = neutral
(bytes match the pilot modal on every compared cell), 1 = NOT neutral,
3 = unreachable.
"""
import argparse
import json
import os
from datetime import datetime, timezone

from harness.config import (
    LOCAL_KEEP_ALIVE,
    LOCAL_MODELS,
    LOCAL_SAMPLING,
    local_pinned_arm,
)
from harness.planes import LocalPlane
from harness.request_builder import canonical_local_body

LOGPROB_FIELDS = {"logprobs": True, "top_logprobs": 5}

# Short-output greedy cells only: the metal open-generation cell is already
# multi-modal without logprobs, so byte comparison there cannot isolate the
# logprobs effect. On cuda all four greedy cells were 1.0 in the pilot.
PROBE_TASKS = ("classification", "extraction", "structured_json", "open_generation")


def pilot_modal_sha(report, box, model_key, task, arm):
    key = f"{box}::{model_key}|{task}|greedy|{arm}"
    entry = report["q1_cells"].get(key)
    if not entry or "metrics" not in entry:
        return None, key
    return entry["metrics"]["modal_sha256"], key


def main():
    parser = argparse.ArgumentParser(description="logprobs byte-neutrality probe")
    parser.add_argument("--base-url", default="http://127.0.0.1:11434")
    parser.add_argument("--label", required=True)
    parser.add_argument("--report", required=True,
                        help="committed study3 report JSON with the pilot modals")
    parser.add_argument("--box", required=True)
    parser.add_argument("--model", default="gpt-oss-20b",
                        help="LOCAL_MODELS key to probe")
    parser.add_argument("--repeats", type=int, default=3)
    parser.add_argument("--keep-alive", default=LOCAL_KEEP_ALIVE)
    parser.add_argument("--out", default="evidence")
    args = parser.parse_args()

    with open(args.report, encoding="utf-8") as fh:
        report = json.load(fh)

    cfg = LOCAL_MODELS[args.model]
    arm = local_pinned_arm(cfg)
    plane = LocalPlane(base_url=args.base_url, name=f"local_{args.label}")
    try:
        version = plane.engine_version()
        digest = plane.model_digest(cfg["tag"])
    except Exception as err:
        print(f"UNREACHABLE: {err}")
        return 3

    from harness.tasks import TASKS

    cells = []
    all_neutral = True
    for task in PROBE_TASKS:
        modal_sha, key = pilot_modal_sha(report, args.box, args.model, task, arm)
        body = canonical_local_body(
            cfg["tag"], TASKS[task]["prompt"], arm,
            options=LOCAL_SAMPLING["greedy"], keep_alive=args.keep_alive,
            extra=LOGPROB_FIELDS,
        )
        shas = []
        exposes = []
        ok = True
        for _ in range(args.repeats):
            result = plane.invoke(body)
            if not result["ok"]:
                ok = False
                shas.append(f'ERROR:{result.get("error_code")}')
                continue
            shas.append(result["text_sha256"])
            exposes.append(bool((plane.last_payload or {}).get("logprobs")))
        distinct = sorted(set(shas))
        matches_pilot = (
            modal_sha is not None and distinct == [modal_sha]
        )
        # Neutrality on cells the pilot measured stable: every probe call
        # must reproduce the pilot's modal bytes exactly.
        pilot_stable = modal_sha is not None and report["q1_cells"][key][
            "metrics"
        ]["modal_share"] == 1.0
        neutral = matches_pilot if pilot_stable else None
        if pilot_stable and not matches_pilot:
            all_neutral = False
        cells.append({
            "cell": key,
            "pilot_modal_sha256": modal_sha,
            "pilot_modal_share": (
                report["q1_cells"][key]["metrics"]["modal_share"]
                if modal_sha else None
            ),
            "probe_shas": shas,
            "probe_distinct": len(distinct),
            "all_ok": ok,
            "logprobs_present_in_responses": exposes,
            "byte_neutral_vs_pilot": neutral,
        })

    evidence = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "base_url": args.base_url,
        "label": args.label,
        "engine_version": version,
        "model": cfg["tag"],
        "model_digest": digest,
        "logprob_fields": LOGPROB_FIELDS,
        "report_compared": args.report,
        "repeats": args.repeats,
        "cells": cells,
        "verdict": {
            "byte_neutral_on_all_stable_cells": all_neutral,
        },
    }
    os.makedirs(args.out, exist_ok=True)
    out_path = os.path.join(args.out, f"logprobs-bytes-probe-{args.label}.json")
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(evidence, fh, indent=2, sort_keys=True)

    for cell in cells:
        print(
            f'{cell["cell"]}: neutral={cell["byte_neutral_vs_pilot"]} '
            f'distinct={cell["probe_distinct"]} '
            f'logprobs_present={all(cell["logprobs_present_in_responses"] or [False])}'
        )
    print(f"VERDICT byte_neutral={all_neutral}")
    print(f"evidence -> {out_path}")
    return 0 if all_neutral else 1


if __name__ == "__main__":
    raise SystemExit(main())
